name: Auto Pull Jsnzkpg
on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00 更新
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Jsnzkpg/Jsnzkpg # 仓库地址
      - name: Pull changes
        run: |
          git checkout main # 切换到主分支
          git pull origin main # 拉取最新代码
          cp Jsnzkpg /Jsnzkpg # 复制文件到目标路径
